# Workflow to deploy to environments
name: Deploy
on:
  push:
    branches: [ main ]
env:
  branch: ''

jobs:
  
  deploy-aws:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    
    steps:
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::388288125913:role/github-role-Role-35MM3616TCT6
          aws-region: us-east-1
      
      - name: Setup Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Package lambda api
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        run: |
          cd src/
          python -m pip install --upgrade pip
          pip install wheel setuptools -t ./
          pip install -r requirements.txt -t ./
          chmod -R 755 .
          zip -r9 ${GITHUB_REF##*/}.zip * -x "*.pyc" -x "requirements.txt" -x "${GITHUB_REF##*/}.zip"
          echo ::set-env name=branch::${GITHUB_REF##*/}
          aws s3 cp ${GITHUB_REF##*/}.zip s3://yotixify-deploy-bucket/${GITHUB_REPOSITORY}/${GITHUB_REF##*/}-3.zip
        
      - name: Deploy w/ AWS Cloudformation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: fast-api-example
          template: ./template.cfn.yml
          no-fail-on-empty-changeset: 1
          parameter-overrides: Environment=${{env.branch}},Repo=${{github.repository }}
          capabilities: CAPABILITY_AUTO_EXPAND, CAPABILITY_IAM
          

      
